### ISSUE TITLE
0.1.3 push to Pupet Forge

### ISSUE THREAD

**Issue by gusnuf** [BIAndrews/puppet-osquery#5]
I'd really like to use the version of this module that has repo_install as a class parameter, but the changes in PR #4 (master commit 2edd935aa243c7cbfa4abbd0622ab86b4c6b4c42) seem not to be on the forge.  metadata.json was not revved in that commit, so I presume it would need to be 0.1.3.

Thanks!

**Comment by bryanandrews** [comment]
On it

**Comment by BIAndrews** [comment]
On it

**Comment by gusnuf** [comment]
Thank you very much!
